# Generated by Django 5.0.8 on 2024-08-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('withdrawal', 'Снятие'), ('transfer', 'Пополнение'), ('fee', 'Оплата')], help_text='Тип операции с балансом', max_length=50, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма операции', max_digits=15, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, help_text='Описание операции', verbose_name='Описание')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='Дата создания операции с банковским балансом пользователя', verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, help_text='Дата изменений данных операции с банковским балансом пользователя', verbose_name='Дата внесений изменений')),
                ('balance', models.ForeignKey(help_text='Операции с банковским балансом пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='balances.balance', verbose_name='Банковский баланс')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('-created_dt',),
            },
        ),
    ]
