# Generated by Django 5.0.8 on 2024-08-07 15:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, help_text='Текущий баланс на счёте', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Баланс на счёте'),
        ),
    ]
